# 개발 환경과 로컬 환경의 중복되는 설정 부분을 default.yaml 에 등록한다.
server:
  port: 3001

db:
  type: 'postgres'
  port: 5432
  database: 'member-app'

jwt:
  expiresIn: 3600

# NODE_ENV가 production 이면 production.yml 파일을 사용
